image: moodlehq/moodle-workplace-plugin-ci:8.0

services:
  - postgres:13
  #- mysql:5.7.26
  - name: selenium/standalone-chrome:3
    alias: selenium-standalone-chrome

variables:
  MOODLE_REPO_WORKPLACE: git@git.in.moodle.com:workplace/workplacedev.git
  MOODLE_BRANCH_WORKPLACE404R: WORKPLACE_ROLLING_404
  MOODLE_BRANCH_WORKPLACE403R: WORKPLACE_ROLLING_403
  MOODLE_BRANCH_WORKPLACE403S: WORKPLACE_403
  MOODLE_BRANCH_WORKPLACE402S: WORKPLACE_402
  MOODLE_BRANCH_WORKPLACE401S: WORKPLACE_401
  MOODLE_BRANCH_WORKPLACE400: WORKPLACE_400
  MOODLE_BRANCH_WORKPLACE311: WORKPLACE_311
  MOODLE_REPO_LMS: git@git.in.moodle.com:moodle/moodle.git
  MOODLE_BRANCH_LMS404: main # TODO WPOS-92 replace with MOODLE_404_STABLE when it is created
  MOODLE_BRANCH_LMS403: MOODLE_403_STABLE
  MOODLE_BRANCH_LMS402: MOODLE_402_STABLE
  MOODLE_BRANCH_LMS401: MOODLE_401_STABLE
  MOODLE_BRANCH_LMS400: MOODLE_400_STABLE
  MOODLE_BRANCH_LMS311: MOODLE_311_STABLE
  MOODLE_BRANCH_LMS310: MOODLE_310_STABLE
  MOODLE_BRANCH_LMS39: MOODLE_39_STABLE
  MOODLE_BEHAT_WDHOST: "http://selenium-standalone-chrome:4444/wd/hub"
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST_AUTH_METHOD: "trust"
  MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  DB: "pgsql"
#  DB: "mysqli"

# Gitlab-ci does not have matrixes, so we have these hidden jobs .setupworkplace and .setuplms to do the set up.
.setupworkplace: &setupworkplace
  before_script:
    - export MOODLE_REPO=$MOODLE_REPO_WORKPLACE
    - export MOODLE_BRANCH=$MOODLE_BRANCH_WORKPLACE404R
    - . prepare-workplace $cibot_sshkey
    - export PLUGINNAME=$(grep 'plugin->component' $CI_PROJECT_DIR/version.php | awk -F\' '{ print $2; }')
    - cd $CI_PROJECT_DIR/..
    - moodle-plugin-ci add-plugin --clone git@git.in.moodle.com:workplace/moodle-theme_workplace.git
    - moodle-plugin-ci add-plugin --clone git@git.in.moodle.com:workplace/moodle-tool_tenant.git
    - moodle-plugin-ci add-plugin --clone git@git.in.moodle.com:workplace/moodle-tool_wp.git
    - moodle-plugin-ci add-plugin --clone git@git.in.moodle.com:workplace/moodle-tool_dynamicrule.git
    - moodle-plugin-ci install --db-host="$DB_HOST" --no-init -vvv
    - cd moodle

codecheck:
  image: moodlehq/moodle-workplace-plugin-ci:8.1
  <<: *setupworkplace
  script:
    - php admin/tool/phpunit/cli/init.php
    - php admin/tool/phpunit/cli/util.php --buildcomponentconfigs
    - . check-start
    - . check version_number
    - . check no_workplace_licenses
    - . check this_plugin_is_part_of "the tool_datewatch plugin for Moodle - http://moodle.org/" --nowplicensecomment
    - . check language_file_sorting
    - . check behat_workplace_tag
    - . check moodle-plugin-ci phplint
    #- . check moodle-plugin-ci phpcpd
    #- . check moodle-plugin-ci phpmd
    - . check moodle-plugin-ci codechecker --max-warnings 0
    - . check moodle-plugin-ci phpdoc
    - . check moodle-plugin-ci validate
    - . check moodle-plugin-ci savepoints
    - . check moodle-plugin-ci mustache
    - . check moodle-plugin-ci grunt --max-lint-warnings 0
    - . check vendor/bin/phpunit --fail-on-risky --disallow-test-output --testsuite tool_dataprivacy_testsuite --filter metadata_registry_test
    - . check vendor/bin/phpunit --fail-on-risky --disallow-test-output --filter "test_all_external_info@${PLUGINNAME}.*"
    - . check vendor/bin/phpunit --fail-on-risky --disallow-test-output --testsuite core_privacy_testsuite --filter provider_test
    - . check moodle-plugin-ci phpunit --coverage-text --fail-on-warning
    - . check-finish
  except:
    - tags

.scriptshorttest: &scriptshorttest
  script:
    # TODO: when all plugins are removed, remove the argument with the sshkey but leave the call to prepare-workplace, it sets up the env
    - . prepare-workplace $cibot_sshkey
    - export PLUGINNAME=$(grep 'plugin->component' $CI_PROJECT_DIR/version.php | awk -F\' '{ print $2; }')
    - cd $CI_PROJECT_DIR/..
    - moodle-plugin-ci install --db-host="$DB_HOST" --no-init -vvv
    - cd moodle
    - php admin/tool/phpunit/cli/init.php
    - php admin/tool/phpunit/cli/util.php --buildcomponentconfigs
    - php -S ${IPADDRESS}:8000 -t $CI_PROJECT_DIR/../moodle > /dev/null 2>&1 &
    #- php admin/tool/behat/cli/init.php --add-core-features-to-theme
    - . check-start
    - . check moodle-plugin-ci phpunit --coverage-text --fail-on-warning
    #- . check moodle-plugin-ci behat --suite default --profile chrome
    - . check-finish

wp403r:
  before_script:
    - export MOODLE_REPO=$MOODLE_REPO_WORKPLACE
    - export MOODLE_BRANCH=$MOODLE_BRANCH_WORKPLACE403R
  <<: *scriptshorttest
  except:
    - master
    - tags
    - /^WORKPLACE_\d+$/

wp403s:
  before_script:
    - export MOODLE_REPO=$MOODLE_REPO_WORKPLACE
    - export MOODLE_BRANCH=$MOODLE_BRANCH_WORKPLACE403S
  <<: *scriptshorttest
  except:
    - master
    - tags
    - /^WORKPLACE_\d+$/

wp402s:
  before_script:
    - export MOODLE_REPO=$MOODLE_REPO_WORKPLACE
    - export MOODLE_BRANCH=$MOODLE_BRANCH_WORKPLACE402S
  <<: *scriptshorttest
  except:
    - master
    - tags
    - /^WORKPLACE_\d+$/

wp401s:
  before_script:
    - export MOODLE_REPO=$MOODLE_REPO_WORKPLACE
    - export MOODLE_BRANCH=$MOODLE_BRANCH_WORKPLACE401S
  <<: *scriptshorttest
  except:
    - master
    - tags
    - /^WORKPLACE_\d+$/

wp400:
  before_script:
    - export MOODLE_REPO=$MOODLE_REPO_WORKPLACE
    - export MOODLE_BRANCH=$MOODLE_BRANCH_WORKPLACE400
  <<: *scriptshorttest
  except:
    - master
    - tags
    - /^WORKPLACE_\d+$/

wp311:
  before_script:
    - export MOODLE_REPO=$MOODLE_REPO_WORKPLACE
    - export MOODLE_BRANCH=$MOODLE_BRANCH_WORKPLACE311
  <<: *scriptshorttest
  except:
    - master
    - tags
    - /^WORKPLACE_\d+$/

lms39:
  image: moodlehq/moodle-workplace-plugin-ci:7.3
  before_script:
    - export MOODLE_REPO=$MOODLE_REPO_LMS
    - export MOODLE_BRANCH=$MOODLE_BRANCH_LMS39
  <<: *scriptshorttest
  except:
    - master
    - tags
    - /^WORKPLACE_\d+$/

lms310:
  image: moodlehq/moodle-workplace-plugin-ci:7.3
  before_script:
    - export MOODLE_REPO=$MOODLE_REPO_LMS
    - export MOODLE_BRANCH=$MOODLE_BRANCH_LMS310
  <<: *scriptshorttest
  except:
    - master
    - tags
    - /^WORKPLACE_\d+$/

lms311:
  before_script:
    - export MOODLE_REPO=$MOODLE_REPO_LMS
    - export MOODLE_BRANCH=$MOODLE_BRANCH_LMS311
  <<: *scriptshorttest
  except:
    - master
    - tags
    - /^WORKPLACE_\d+$/

lms400:
  before_script:
    - export MOODLE_REPO=$MOODLE_REPO_LMS
    - export MOODLE_BRANCH=$MOODLE_BRANCH_LMS400
  <<: *scriptshorttest
  except:
    - master
    - tags
    - /^WORKPLACE_\d+$/

lms401:
  before_script:
    - export MOODLE_REPO=$MOODLE_REPO_LMS
    - export MOODLE_BRANCH=$MOODLE_BRANCH_LMS401
  <<: *scriptshorttest
  except:
    - master
    - tags
    - /^WORKPLACE_\d+$/

lms402:
  before_script:
    - export MOODLE_REPO=$MOODLE_REPO_LMS
    - export MOODLE_BRANCH=$MOODLE_BRANCH_LMS402
  <<: *scriptshorttest
  except:
    - master
    - tags
    - /^WORKPLACE_\d+$/

lms403:
  before_script:
    - export MOODLE_REPO=$MOODLE_REPO_LMS
    - export MOODLE_BRANCH=$MOODLE_BRANCH_LMS403
  <<: *scriptshorttest
  except:
    - master
    - tags
    - /^WORKPLACE_\d+$/

lms404:
  image: moodlehq/moodle-workplace-plugin-ci:8.1
  before_script:
    - export MOODLE_REPO=$MOODLE_REPO_LMS
    - export MOODLE_BRANCH=$MOODLE_BRANCH_LMS404
  <<: *scriptshorttest
  except:
    - master
    - tags
    - /^WORKPLACE_\d+$/
